# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ParkingSpot(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, full: bool=None, time: datetime=None, user: int=None):  # noqa: E501
        """ParkingSpot - a model defined in Swagger

        :param id: The id of this ParkingSpot.  # noqa: E501
        :type id: int
        :param name: The name of this ParkingSpot.  # noqa: E501
        :type name: str
        :param full: The full of this ParkingSpot.  # noqa: E501
        :type full: bool
        :param time: The time of this ParkingSpot.  # noqa: E501
        :type time: datetime
        :param user: The user of this ParkingSpot.  # noqa: E501
        :type user: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'full': bool,
            'time': datetime,
            'user': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'full': 'full',
            'time': 'time',
            'user': 'user'
        }

        self._id = id
        self._name = name
        self._full = full
        self._time = time
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'ParkingSpot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParkingSpot of this ParkingSpot.  # noqa: E501
        :rtype: ParkingSpot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ParkingSpot.


        :return: The id of this ParkingSpot.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ParkingSpot.


        :param id: The id of this ParkingSpot.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ParkingSpot.


        :return: The name of this ParkingSpot.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ParkingSpot.


        :param name: The name of this ParkingSpot.
        :type name: str
        """

        self._name = name

    @property
    def full(self) -> bool:
        """Gets the full of this ParkingSpot.


        :return: The full of this ParkingSpot.
        :rtype: bool
        """
        return self._full

    @full.setter
    def full(self, full: bool):
        """Sets the full of this ParkingSpot.


        :param full: The full of this ParkingSpot.
        :type full: bool
        """

        self._full = full

    @property
    def time(self) -> datetime:
        """Gets the time of this ParkingSpot.


        :return: The time of this ParkingSpot.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this ParkingSpot.


        :param time: The time of this ParkingSpot.
        :type time: datetime
        """

        self._time = time

    @property
    def user(self) -> int:
        """Gets the user of this ParkingSpot.


        :return: The user of this ParkingSpot.
        :rtype: int
        """
        return self._user

    @user.setter
    def user(self, user: int):
        """Sets the user of this ParkingSpot.


        :param user: The user of this ParkingSpot.
        :type user: int
        """

        self._user = user
