# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ParkingSpot(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, name: str=None, location: str=None, full: bool=None):  # noqa: E501
        """ParkingSpot - a model defined in Swagger

        :param id: The id of this ParkingSpot.  # noqa: E501
        :type id: int
        :param name: The name of this ParkingSpot.  # noqa: E501
        :type name: str
        :param location: The location of this ParkingSpot.  # noqa: E501
        :type location: str
        :param full: The full of this ParkingSpot.  # noqa: E501
        :type full: bool
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'location': str,
            'full': bool
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'location': 'location',
            'full': 'full'
        }

        self._id = id
        self._name = name
        self._location = location
        self._full = full

    @classmethod
    def from_dict(cls, dikt) -> 'ParkingSpot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ParkingSpot of this ParkingSpot.  # noqa: E501
        :rtype: ParkingSpot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ParkingSpot.

        parking spot id unique for each  # noqa: E501

        :return: The id of this ParkingSpot.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ParkingSpot.

        parking spot id unique for each  # noqa: E501

        :param id: The id of this ParkingSpot.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this ParkingSpot.

        show the name of the parking spot  # noqa: E501

        :return: The name of this ParkingSpot.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ParkingSpot.

        show the name of the parking spot  # noqa: E501

        :param name: The name of this ParkingSpot.
        :type name: str
        """

        self._name = name

    @property
    def location(self) -> str:
        """Gets the location of this ParkingSpot.

        the position of the parking spot  # noqa: E501

        :return: The location of this ParkingSpot.
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location: str):
        """Sets the location of this ParkingSpot.

        the position of the parking spot  # noqa: E501

        :param location: The location of this ParkingSpot.
        :type location: str
        """

        self._location = location

    @property
    def full(self) -> bool:
        """Gets the full of this ParkingSpot.


        :return: The full of this ParkingSpot.
        :rtype: bool
        """
        return self._full

    @full.setter
    def full(self, full: bool):
        """Sets the full of this ParkingSpot.


        :param full: The full of this ParkingSpot.
        :type full: bool
        """

        self._full = full
