# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, uid: int=None, name: str=None, password: str=None, status: str=None, spot_id: int=None, park_time: str=None, park_hour: int=None):  # noqa: E501
        """User - a model defined in Swagger

        :param uid: The uid of this User.  # noqa: E501
        :type uid: int
        :param name: The name of this User.  # noqa: E501
        :type name: str
        :param password: The password of this User.  # noqa: E501
        :type password: str
        :param status: The status of this User.  # noqa: E501
        :type status: str
        :param spot_id: The spot_id of this User.  # noqa: E501
        :type spot_id: int
        :param park_time: The park_time of this User.  # noqa: E501
        :type park_time: str
        :param park_hour: The park_hour of this User.  # noqa: E501
        :type park_hour: int
        """
        self.swagger_types = {
            'uid': int,
            'name': str,
            'password': str,
            'status': str,
            'spot_id': int,
            'park_time': str,
            'park_hour': int
        }

        self.attribute_map = {
            'uid': 'uid',
            'name': 'name',
            'password': 'password',
            'status': 'status',
            'spot_id': 'spot_id',
            'park_time': 'park_time',
            'park_hour': 'park_hour'
        }

        self._uid = uid
        self._name = name
        self._password = password
        self._status = status
        self._spot_id = spot_id
        self._park_time = park_time
        self._park_hour = park_hour

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uid(self) -> int:
        """Gets the uid of this User.

        id of the user  # noqa: E501

        :return: The uid of this User.
        :rtype: int
        """
        return self._uid

    @uid.setter
    def uid(self, uid: int):
        """Sets the uid of this User.

        id of the user  # noqa: E501

        :param uid: The uid of this User.
        :type uid: int
        """

        self._uid = uid

    @property
    def name(self) -> str:
        """Gets the name of this User.

        name of the user  # noqa: E501

        :return: The name of this User.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this User.

        name of the user  # noqa: E501

        :param name: The name of this User.
        :type name: str
        """

        self._name = name

    @property
    def password(self) -> str:
        """Gets the password of this User.


        :return: The password of this User.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this User.


        :param password: The password of this User.
        :type password: str
        """

        self._password = password

    @property
    def status(self) -> str:
        """Gets the status of this User.

        if the user is parking  # noqa: E501

        :return: The status of this User.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this User.

        if the user is parking  # noqa: E501

        :param status: The status of this User.
        :type status: str
        """

        self._status = status

    @property
    def spot_id(self) -> int:
        """Gets the spot_id of this User.

        the id of parking spot  # noqa: E501

        :return: The spot_id of this User.
        :rtype: int
        """
        return self._spot_id

    @spot_id.setter
    def spot_id(self, spot_id: int):
        """Sets the spot_id of this User.

        the id of parking spot  # noqa: E501

        :param spot_id: The spot_id of this User.
        :type spot_id: int
        """

        self._spot_id = spot_id

    @property
    def park_time(self) -> str:
        """Gets the park_time of this User.


        :return: The park_time of this User.
        :rtype: str
        """
        return self._park_time

    @park_time.setter
    def park_time(self, park_time: str):
        """Sets the park_time of this User.


        :param park_time: The park_time of this User.
        :type park_time: str
        """

        self._park_time = park_time

    @property
    def park_hour(self) -> int:
        """Gets the park_hour of this User.


        :return: The park_hour of this User.
        :rtype: int
        """
        return self._park_hour

    @park_hour.setter
    def park_hour(self, park_hour: int):
        """Sets the park_hour of this User.


        :param park_hour: The park_hour of this User.
        :type park_hour: int
        """

        self._park_hour = park_hour
