---
swagger: "2.0"
info:
  version: "1.0.0"
  title: "Parking System"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/"
schemes:
- "http"
paths:
  /Login:
    get:
      summary: "Login into server"
      description: "check user crediential"
      operationId: "login_get"
      produces:
      - "application/json"
      parameters:
      - name: "uid"
        in: "query"
        description: "the user id"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Successful Login"
          schema:
            type: "string"
            example: "OKAY"
        400:
          description: "Incorrect Password"
      security:
      - basicAuth: []
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /ParkingSpots:
    get:
      operationId: "parking_spots_get"
      parameters:
      - name: "range"
        in: "query"
        description: "show the list of parking spots by filter [\"All\", \"Available\"\
          , \"Taken\"]"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful search"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ParkingSpot"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /ParkingSpots/{id}:
    get:
      operationId: "parking_spots_id_get"
      parameters:
      - name: "id"
        in: "path"
        description: "parking spot id"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful finding"
          schema:
            $ref: "#/definitions/ParkingSpot"
        400:
          description: "Fail"
      security:
      - basicAuth: []
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
    post:
      description: "the user id"
      operationId: "parking_spots_id_post"
      parameters:
      - name: "id"
        in: "path"
        description: "parking spot id"
        required: true
        type: "integer"
      - name: "op"
        in: "query"
        description: "the operation the user want to act [\"check_in\", \"check_out\"\
          ]"
        required: true
        type: "string"
      - name: "uid"
        in: "query"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Successful CheckIn Or CheckOut"
        400:
          description: "Fail"
      security:
      - basicAuth: []
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
securityDefinitions:
  basicAuth:
    type: "basic"
definitions:
  ParkingSpot:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      full:
        type: "boolean"
      time:
        type: "string"
        format: "date-time"
      user:
        type: "integer"
        format: "int32"
    example:
      name: "name"
      id: 0
      time: "2000-01-23T04:56:07.000+00:00"
      user: 6
      full: true
  User:
    type: "object"
    properties:
      uid:
        type: "integer"
        format: "int32"
      username:
        type: "string"
      password:
        type: "string"
        format: "password"
      parking:
        type: "boolean"
      spot:
        type: "integer"
        format: "int32"
